apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources: 
      requests:
        cpu: "100"
        memory: "100Gi"
      limits:
        cpu: "100"
        memory: "150Gi"  
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  