apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-proxy
data:
  nginx.conf: |
    worker_processes 4;
    events { worker_connections 1024; }
    http {
        server {
            listen 80;
            location / {
                proxy_pass https://brainupgrade.in;
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: ambassador
        image: nginx
        ports:
        - containerPort: 80        
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-proxy
