apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - name: frontend
    image: anshshrivastava/smartbankfrontend:v4
    startupProbe:
      httpGet:
        path: /
        port: 80
      failureThreshold: 2
      successThreshold: 1
      periodSeconds: 5
      initialDelaySeconds: 0
