apiVersion: v1
kind: Pod
metadata:
  name: readiness
spec:
  containers:
  - name: readiness
    image: k8s.gcr.io/liveness
    args:
    - /server
    readinessProbe:
      httpGet:
        path: /readiness
        port: 8080
      initialDelaySeconds: 0
      periodSeconds: 1
      successThreshold: 1
      failureThreshold: 10
