apiVersion: v1
kind: Pod
metadata:
  name: liveness
spec:
  containers:
  - name: liveness
    image: brainupgrade/tshoot
    command:
    - /bin/sh
    args:
    - -c
    - while true; do touch /tmp/healthy;sleep 15; rm -rf /tmp/healthy;sleep 10;touch /tmp/healthy;done
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 0
      periodSeconds: 1
      successThreshold: 1
      failureThreshold: 5
