apiVersion: v1
kind: Pod
metadata:
  name: probe-liveness-http
spec:
  containers:
  - name: probe-liveness-http
    image: anshshrivastava/smartbankfrontend:v4
    args:
    - /server
    livenessProbe:
      httpGet:
        path: /
        port: 80
        httpHeaders:
        - name: Custom-Header
          value: Awesome
      initialDelaySeconds: 3
      periodSeconds: 3
      successThreshold: 1
      failureThreshold: 1
