apiVersion: v1
kind: Pod
metadata:
  name: volume-emptydir
spec:
  containers:
  - image: nginx
    name: test-container
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
    resources:
      limits:
        cpu: "20m"
        memory: "50Mi"  
  volumes:
  - name: cache-volume
    emptyDir: {}