apiVersion: v1
kind: Pod
metadata:
  name: volume-ebs
spec:
  nodeName: ip-172-31-58-74.ec2.internal
  containers:
  - image: nginx
    name: test-container
    volumeMounts:
    - mountPath: /test-ebs
      name: ebs-volume
    resources:
      limits:
        cpu: "20m"
        memory: "50Mi"  
  volumes:
  - name: ebs-volume
    # This AWS EBS volume must already exist.
    awsElasticBlockStore:
      volumeID: vol-081b401a592b794a2
      fsType: ext4