apiVersion: v1
kind: Pod
metadata:
  name: volume-ebs
spec:
  imagePullSecrets:
    - name: regcred
  nodeName: ip-172-31-101-240.ec2.internal
  containers:
  - image: nginx
    name: test-container
    volumeMounts:
    - mountPath: /test-ebs
      name: ebs-volume
    resources:
      limits:
        cpu: "20m"
        memory: "50Mi"  
  volumes:
  - name: ebs-volume
    # This AWS EBS volume must already exist.
    awsElasticBlockStore:
      volumeID: vol-0030e0d998eda8c78
      fsType: ext4