apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ebs
  labels:
    type: ebs
spec:
    storageClassName: gp2
    accessModes: 
    - ReadWriteMany
    capacity:
      storage: 1Gi
    awsElasticBlockStore:
      volumeID: vol-0b4e04c91db8e0ce0
      fsType: ext4
---
apiVersion: v1
kind: Pod
metadata:
  name: pv-ebs-user
spec:
  # nodeSelector:
  #  topology.kubernetes.io/zone: us-east-1c
  containers:
  - image: nginx
    name: test-container
    volumeMounts:
    - mountPath: /test-ebs
      name: ebs-volume
  volumes:
  - name: ebs-volume
    persistentVolumeClaim:
      claimName: pv-ebs-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-ebs-pvc
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi             
  selector: 
    matchLabels: 
      type: ebs
