apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
    - name: test
      image: busybox
      command:
      - sh
      - -c
      - sleep 300
      volumeMounts:
        - name: config-vol
          mountPath: /etc/config
  volumes:
    - name: config-vol
      configMap:
        name: log-config
        items:
          - key: log_level
            path: log_level
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: log-config
data:
  log_level: |
    debug=true
