apiVersion: v1
kind: Pod
metadata:
  name: pv-ebs-2
spec:
  nodeSelector:
    topology.kubernetes.io/zone: ap-south-1a
  containers:
  - image: nginx
    name: test-container
    volumeMounts:
    - mountPath: /test-ebs
      name: ebs-volume
  volumes:
  - name: ebs-volume
    persistentVolumeClaim:
      claimName: pv-ebs-pvc-2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-ebs-pvc-2
spec:
  storageClassName: gp3
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi             
  selector: 
    matchLabels: 
      type: gp3
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ebs-2
  labels:
    type: gp3
spec:
    storageClassName: gp3
    accessModes: 
    - ReadWriteMany
    capacity:
      storage: 1Gi
    awsElasticBlockStore:
      volumeID: vol-019fea9d477209e08
      fsType: ext4
