apiVersion: v1
kind: Pod
metadata:
  name: pv-ebs-user
spec:
  nodeSelector:
   topology.kubernetes.io/zone: us-east-1c
  containers:
  - image: nginx
    name: test-container
    volumeMounts:
    - mountPath: /test-ebs
      name: ebs-volume
  volumes:
  - name: ebs-volume
    persistentVolumeClaim:
      claimName: pv-ebs-pvc
