kind: Pod
apiVersion: v1
metadata:
  name: test-efs-pod
spec:
  containers:
  - name: test-pod
    image: wordpress:5.3.2-apache
    volumeMounts:
      - name: efs-pvc
        mountPath: "/var/www/html"
  restartPolicy: "Never"
  volumes:
    - name: efs-pvc
      persistentVolumeClaim:
        claimName: efs-www-in
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-www-in
  labels:
    app: efs-www-in
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: fs-23da34g9.efs.us-east-1.amazonaws.com
    path: "/www"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs-www-in
  labels:
    app: efs-www-in
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi    
  selector: 
    matchLabels: 
      app: efs-www-in
