kind: Pod
apiVersion: v1
metadata:
  name: test-efs-pod
spec:
  containers:
  - name: test-pod
    image: wordpress:5.3.2-apache
    volumeMounts:
      - name: efs-pvc
        mountPath: "/var/www/html"
  restartPolicy: "Never"
  volumes:
    - name: efs-pvc
      persistentVolumeClaim:
        claimName: efs-www-in
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-www-in
  labels:
    app: efs-www-in
spec:
  storageClassName: efs-sc
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-014cf21e1ac0676ff 
  # nfs:
  #   server: fs-014cf21e1ac0676ff.efs.ap-south-1.amazonaws.com
  #   path: "/www"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs-www-in
  labels:
    app: efs-www-in
spec:
  storageClassName: efs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi    
  selector: 
    matchLabels: 
      app: efs-www-in
