apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logger-pvc
  labels:
    app: logger
spec:
  storageClassName: storageclass-generic
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi