apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: rajesh-cluster
  region: ap-south-1
  version: "1.20"
managedNodeGroups:
- name: ng-1
  labels:
    role: ng-1
  instanceType: t3a.small
  spot: true
  minSize: 1
  maxSize: 2
  desiredCapacity: 1
  volumeSize: 20
