kind: PersistentVolume
apiVersion: v1
metadata:
  name: www
  labels:
    app: www
    volume-type: gp2
    aws-availability-zone: us-east-1
spec:
  capacity:
    storage: 1Gi
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  awsElasticBlockStore:
    volumeID: vol-081b401a592b794a2  # insert volume id
    fsType: ext4
  persistentVolumeReclaimPolicy: Retain  