apiVersion: v1
kind: ConfigMap
metadata:
  name: ambassador-nginx-config
data:
  nginx.conf: |
    worker_processes 1;
    worker_rlimit_nofile 4096;
    events {
      worker_connections 512;
    }
    http {
      include mime.types;

      server {
        listen 80;

        access_log /dev/stdout;
        error_log  /dev/stderr;

        location / {
          proxy_http_version 1.1;
          # proxy_set_header Host https://google.com;

          proxy_pass https://brainupgrade.in;
        }
      }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: ambassador
  labels:
    app: ambassador
spec:
  containers:
  - name: main
    image: nginx
    volumeMounts:
    - name: shared-content
      mountPath: /usr/share/nginx/html
  - name: sidecar
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh"]
    args: ["-c","while true;do wget -O /tmp/index.html localhost:80 ;sleep 30;done"]
    volumeMounts:
    - name: shared-content
      mountPath: /tmp    
  - name: ambassador
    image: nginx
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80        
    volumeMounts:
      - name: nginx-config
        mountPath: /etc/nginx/nginx.conf
        subPath: nginx.conf
  volumes:
    - name: nginx-config
      configMap:
        name: ambassador-nginx-config
    - name: shared-content
      emptyDir: {}
