apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: autoscaling-rajesh
  region: ap-south-1
  version: "1.20"
availabilityZones:
- ap-south-1a
- ap-south-1b
managedNodeGroups:
- name: managed-nodes
  labels:
    role: managed-nodes
  instanceType: t3a.small
  spot: true
  minSize: 1
  maxSize: 2
  desiredCapacity: 1
  volumeSize: 20
